# Generated by Django 6.0.5 on 2026-05-23 10:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('movement_type', models.CharField(choices=[('ENTRY', 'Entrada'), ('OUTPUT', 'Saída'), ('ADJUSTMENT', 'Ajuste')], max_length=20, verbose_name='Tipo de movimentação')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('previous_stock', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Estoque anterior')),
                ('new_stock', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Novo estoque')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.material', verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Movimentação de estoque',
                'verbose_name_plural': 'Movimentações de estoque',
                'ordering': ['-created_at'],
            },
        ),
    ]
