# Generated by Django 6.0.5 on 2026-05-24 05:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockmovement'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('abbreviation', models.CharField(max_length=20, unique=True, verbose_name='Abreviação')),
                ('unit_type', models.CharField(choices=[('UNIT', 'Unidade'), ('PACKAGE', 'Embalagem'), ('WEIGHT', 'Peso'), ('LENGTH', 'Comprimento'), ('VOLUME', 'Volume'), ('AREA', 'Área')], default='UNIT', max_length=20, verbose_name='Tipo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Unidade de medida',
                'verbose_name_plural': 'Unidades de medida',
                'ordering': ['name'],
            },
        ),
    ]
