# Generated by Django 6.0.5 on 2026-05-24 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_unitofmeasure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='unit',
        ),
        migrations.AddField(
            model_name='material',
            name='conversion_factor',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Quantidade da unidade de estoque gerada por 1 unidade de compra.', max_digits=10, verbose_name='Fator de conversão'),
        ),
        migrations.AddField(
            model_name='material',
            name='purchase_unit',
            field=models.ForeignKey(default='d97bf274-c55b-40b5-8775-aa01084229b0', on_delete=django.db.models.deletion.PROTECT, related_name='materials_as_purchase_unit', to='inventory.unitofmeasure', verbose_name='Unidade de compra'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='stock_unit',
            field=models.ForeignKey(default='d97bf274-c55b-40b5-8775-aa01084229b0', on_delete=django.db.models.deletion.PROTECT, related_name='materials_as_stock_unit', to='inventory.unitofmeasure', verbose_name='Unidade de estoque'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Preço de custo por unidade de compra.', max_digits=10, verbose_name='Preço de custo'),
        ),
        migrations.AlterField(
            model_name='material',
            name='current_stock',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Estoque armazenado sempre na unidade de estoque.', max_digits=10, verbose_name='Estoque atual'),
        ),
        migrations.AlterField(
            model_name='material',
            name='minimum_stock',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Estoque mínimo na unidade de estoque.', max_digits=10, verbose_name='Estoque mínimo'),
        ),
    ]
