# Generated by Django 6.0.5 on 2026-05-24 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_material_unit_material_conversion_factor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovement',
            name='quantity',
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='converted_quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Quantidade convertida'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='purchase_quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Quantidade comprada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='purchase_unit',
            field=models.ForeignKey(default='d97bf274-c55b-40b5-8775-aa01084229b0', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_movements', to='inventory.unitofmeasure', verbose_name='Unidade comprada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='stock_unit',
            field=models.ForeignKey(default='d97bf274-c55b-40b5-8775-aa01084229b0', on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.unitofmeasure', verbose_name='Unidade de estoque'),
            preserve_default=False,
        ),
    ]
