# Generated by Django 6.0.5 on 2026-05-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_stockmovement_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('SIMPLE', 'Simples'), ('FRACTIONED', 'Fracionado'), ('PACKAGE', 'Embalagem'), ('KIT', 'Kit')], default='SIMPLE', max_length=20, verbose_name='Tipo de material'),
        ),
    ]
